"""Versión 1.4: navegación, perfil de operador, remolques por división, combustible y Excel. PCS_TEST_USER/PCS_TEST_PASS"""
import subprocess, time, sys, os, json, re
from playwright.sync_api import sync_playwright
APP=os.path.abspath(os.path.join(os.path.dirname(__file__),'..')); os.makedirs('shots',exist_ok=True)
U=os.environ['PCS_TEST_USER']; P=os.environ['PCS_TEST_PASS']; BASE='http://127.0.0.1:8774/index.html'
srv=subprocess.Popen([sys.executable,'-m','http.server','8774','--bind','127.0.0.1'],cwd=APP,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL); time.sleep(1)
log=[]; errs=[]
def ok(c,m): log.append(('OK  ' if c else 'FAIL')+' '+m)
def shot(pg,n): pg.screenshot(path=f'shots/{n}.png')
def form(pg): pg.wait_for_selector('.op-form'); pg.wait_for_timeout(300)
def submit(pg): pg.locator('.op-form button[type=submit]').click(); pg.wait_for_timeout(500)
def recarga(pg, date, time_, odo, lit, amt, full=True, notes=''):
    pg.locator('[data-new]').first.click(); form(pg)
    pg.fill('.op-form [name=date]',date); pg.fill('.op-form [name=time]',time_); pg.fill('.op-form [name=odometer]',str(odo)); pg.fill('.op-form [name=liters]',str(lit)); pg.fill('.op-form [name=amount]',str(amt))
    if not full: pg.locator('[data-full="0"]').click()
    if notes: pg.fill('.op-form [name=notes]',notes)
    submit(pg)
try:
  with sync_playwright() as p:
    b=p.chromium.launch(); ctx=b.new_context(viewport={'width':390,'height':844},device_scale_factor=2,is_mobile=True,has_touch=True,service_workers='block',accept_downloads=True)
    ctx.route(lambda u:'cdnjs' in u or 'fonts.g' in u, lambda r:r.abort())
    pg=ctx.new_page(); pg.on('pageerror',lambda e:errs.append(str(e)))
    pg.goto(BASE); pg.wait_for_selector('.login'); pg.fill('#lg-user',U); pg.fill('#lg-pass',P); pg.click('#lg-go'); pg.wait_for_selector('.login',state='detached'); pg.wait_for_timeout(900)
    if pg.locator('.asheet').count(): pg.get_by_role('button',name='Ahora no').click()
    # ===== Navegación =====
    tabs=[x.inner_text().strip() for x in pg.locator('.tabbar a, .tabbar button').all()]
    # En un celular de 390 px «Administración» se muestra abreviada («Admin.»); su nombre accesible es el completo
    ok(tabs==['Inicio','Operación','Nuevo','Admin.','Ajustes'] and pg.locator('.tabbar [data-tab="admin"]').get_attribute('aria-label')=='Administración','barra principal: '+' | '.join(tabs))
    ics=pg.locator('.div-ic svg.ic').count()
    ok(ics==2 and pg.locator('.div-ic img').count()==0,'Inicio usa íconos de línea para Puerto y Campo (sin ilustraciones rasterizadas)')
    shot(pg,'n01_inicio')
    pg.locator('.tabbar [data-tab="admin"]').click(); pg.wait_for_timeout(600)
    cards=[x.inner_text().split('\n')[0] for x in pg.locator('.mod-card').all()]; ok(cards==['Operadores','Documentos','Catálogos'],'Administración: '+', '.join(cards)); shot(pg,'n02_admin')
    pg.locator('.tabbar [data-tab="settings"]').click(); pg.wait_for_timeout(600)
    ok('Catálogos' not in pg.locator('.page').inner_text() and 'Administrar catálogos' not in pg.locator('.page').inner_text(),'Ajustes ya no contiene Catálogos')
    pg.locator('.tabbar .tab-new').click(); pg.wait_for_timeout(400)
    nopts=[x.inner_text().split('\n')[0] for x in pg.locator('.new-opt').all()]; ok(nopts==['Nota de entrega','Asignación de unidades','Viaje de operador','Recarga de combustible'],'Nuevo: '+', '.join(nopts)); shot(pg,'n03_nuevo'); pg.keyboard.press('Escape')
    # ===== Remolques: tipo y filtros =====
    pg.goto(BASE+'#/catalogos/trailers'); pg.wait_for_timeout(700)
    for placas,tipo in [('61-UT-2M','chasis'),('63-VB-1R','chasis'),('08-UW-6K','jaula'),('13-UW-6K','tolva')]:
        pg.locator('[data-id]',has_text=placas).click(); pg.wait_for_selector('.cat-form'); pg.select_option('.cat-form [name=type]',tipo); pg.locator('.cat-form button[type=submit]').click(); pg.wait_for_timeout(400)
    counts={}
    for k in ['todos','chasis','jaula','tolva','']:
        pg.locator(f'[data-tt="{k}"]').click(); pg.wait_for_timeout(150); counts[k or 'sin']=pg.locator('[data-list] .row').count()
    ok(counts=={'todos':8,'chasis':2,'jaula':1,'tolva':1,'sin':4},'filtros de remolques: '+str(counts))
    pg.locator('[data-tt="todos"]').click(); pg.wait_for_timeout(150); ok('Sin clasificar' in pg.locator('[data-list]').inner_text(),'los remolques sin tipo se muestran como «Sin clasificar»'); shot(pg,'n04_remolques')
    # Puerto: prefiltra chasis
    pg.goto(BASE+'#/'); pg.wait_for_timeout(500); pg.locator('[data-new="puerto"]').click(); pg.wait_for_selector('.co-opt'); pg.locator('.co-opt[data-k="perconsur"]').click(); pg.wait_for_timeout(800)
    pg.locator('[data-w="next"]').click(); pg.wait_for_timeout(600); pg.locator('[data-pick="placasR"]').click(); pg.wait_for_selector('.picker'); pg.wait_for_timeout(300)
    t=pg.locator('.picker-list').inner_text()
    ok(t.startswith('Chasis portacontenedor') and '61-UT-2M' in t and '08-UW-6K' not in t and '13-UW-6K' not in t and 'Ver todos los remolques (2 más)' in t,'Puerto: muestra primero chasis; jaulas y tolvas ocultas')
    shot(pg,'n05_puerto_remolques'); pg.locator('[data-all]').click(); pg.wait_for_timeout(200)
    ok('08-UW-6K' in pg.locator('.picker-list').inner_text() and 'Otros tipos' in pg.locator('.picker-list').inner_text(),'Puerto: «Ver todos» muestra jaulas y tolvas para excepciones')
    pg.locator('.pk-row[data-v="08-UW-6K"]').click(); pg.wait_for_timeout(300); ok(pg.locator('[data-pick="placasR"] .pv-v').inner_text()=='08-UW-6K','se puede elegir un remolque de otro tipo como excepción')
    pg.locator('[data-w="close"]').click(); pg.wait_for_timeout(500)
    # Campo: prefiltra jaulas y tolvas
    pg.locator('[data-new="campo"]').click(); pg.wait_for_timeout(800); pg.locator('[data-w="next"]').click(); pg.wait_for_timeout(600)
    pg.locator('[data-pick="units.0.pr"]').click(); pg.wait_for_selector('.picker'); pg.wait_for_timeout(300); t=pg.locator('.picker-list').inner_text()
    ok(t.startswith('Jaulas y tolvas') and '08-UW-6K' in t and '13-UW-6K' in t and '61-UT-2M' not in t,'Campo: muestra primero jaulas y tolvas; chasis ocultos'); shot(pg,'n06_campo_remolques')
    pg.locator('.pk-row[data-v="13-UW-6K"]').click(); pg.wait_for_timeout(300)
    ok(pg.locator('[data-tipo="Tolva"].on').count()==1,'el tipo guardado del remolque (tolva) completa el tipo de transporte')
    pg.locator('[data-w="close"]').click(); pg.wait_for_timeout(500)
    # ===== Perfil del operador =====
    pg.goto(BASE+'#/operadores'); pg.wait_for_timeout(600); pg.locator('.op-row',has_text='Pedro Urzúa').click(); pg.wait_for_timeout(700)
    ok(pg.locator('.profile').count()==1 and 'Sin capturar' in pg.locator('.profile').inner_text(),'ficha: perfil en modo lectura primero'); shot(pg,'n07_perfil_vacio')
    pg.locator('[data-profile]').first.click(); form(pg)
    pg.locator('.op-form [data-ph]').nth(1).set_input_files('foto.jpg'); pg.wait_for_timeout(1500)
    pg.fill('.op-form [name=rfc]','urss 800101 ab1'); pg.fill('.op-form [name=curp]','urss800101hjclrd09'); pg.fill('.op-form [name=licNumber]','jal 123456')
    pg.fill('.op-form [name=licType]','Federal tipo E'); pg.fill('.op-form [name=licExpires]','2027-03-15')
    ok(pg.locator('.op-form [name=rfc]').input_value()=='URSS800101AB1' and pg.locator('.op-form [name=curp]').input_value()=='URSS800101HJCLRD09','RFC y CURP en mayúsculas y sin espacios')
    shot(pg,'n08_editar'); submit(pg); pg.wait_for_timeout(600)
    prof=pg.locator('.profile').inner_text()
    ok('URSS800101AB1' in prof and 'URSS800101HJCLRD09' in prof and 'JAL123456' in prof and 'Vence 15/03/2027' in prof,'perfil actualizado con RFC, CURP y licencia')
    ok(pg.locator('.profile .av.loaded').count()==1,'la fotografía aparece como avatar en la ficha'); shot(pg,'n09_perfil')
    pg.reload(); pg.wait_for_timeout(1500)
    ok('URSS800101AB1' in pg.locator('.profile').inner_text() and pg.locator('.profile .av.loaded').count()==1,'los datos y la foto persisten al recargar')
    size=pg.evaluate('''async()=>{const db=await new Promise(r=>{const q=indexedDB.open('perconsur');q.onsuccess=()=>r(q.result)});const a=await new Promise(r=>{const q=db.transaction('attachments').objectStore('attachments').getAll();q.onsuccess=()=>r(q.result)});const f=a.find(x=>x.kind==='avatar');return f?f.size:0}''')
    ok(0<size<120000,f'foto comprimida antes de guardar: {size//1024} KB (original 82 KB a 1600 px, ahora 480 px)')
    pg.goto(BASE+'#/operadores'); pg.wait_for_timeout(900); ok(pg.locator('.op-row',has_text='Pedro Urzúa').locator('.av.loaded').count()==1,'avatar en el listado de operadores'); shot(pg,'n10_listado_foto')
    pg.locator('.op-row',has_text='Pedro Urzúa').click(); pg.wait_for_timeout(600)
    pg.locator('[data-tab="estados"]').click(); pg.wait_for_timeout(300); ok('Generar PDF del estado de cuenta' in pg.locator('.op-tab').inner_text(),'pestaña Estados de cuenta en la ficha')
    # ===== Combustible =====
    pg.locator('.tabbar [data-tab="op"]').click(); pg.wait_for_timeout(700); shot(pg,'n11_operacion')
    pg.locator('.mod-card[href="#/operacion/combustible"]').click(); pg.wait_for_timeout(800)
    pg.locator('[data-new]').first.click(); pg.wait_for_selector('.picker'); pg.locator('.pk-row',has_text='U21').click(); form(pg)
    pg.fill('.op-form [name=date]','2026-10-01'); pg.fill('.op-form [name=time]','08:00'); pg.fill('.op-form [name=odometer]','125,430'); pg.fill('.op-form [name=liters]','300'); pg.fill('.op-form [name=amount]','7350')
    ok('$24.50' in pg.locator('[data-ppl]').inner_text(),'precio por litro calculado en vivo: '+pg.locator('[data-ppl]').inner_text()); shot(pg,'n12_form'); submit(pg)
    pg.goto(BASE+'#/operacion/combustible'); pg.wait_for_timeout(700); pg.locator('.unit-chips .chip',has_text='U21').click(); pg.wait_for_timeout(700)
    ok('Rendimiento pendiente' in pg.locator('.page').inner_text(),'con un solo tanque lleno: «Rendimiento pendiente», no inventa un valor')
    recarga(pg,'2026-10-02','09:00',125700,100,2450,False); recarga(pg,'2026-10-03','10:00',126000,80,1960,False); recarga(pg,'2026-10-05','11:00',126330,120,2940,True)
    ok(pg.locator('.perf-v').inner_text().startswith('3.00'),'parciales 100 + 80 + tanque lleno 120 = 300 L en 900 km → 3.00 km/L')
    pg.locator('.fuel-row').first.click(); pg.wait_for_selector('.calc-box'); calc=pg.locator('.bsheet-body').inner_text()
    ok('900 ÷ 300.00 = 3.00 km/L' in calc and '300.00 ÷ 900 × 100 = 33.33 L/100 km' in calc and '01/10/2026 → 05/10/2026' in calc,'detalle del cálculo auditable (periodo, odómetros, recargas, operaciones)')
    shot(pg,'n13_detalle_calculo'); pg.keyboard.press('Escape'); pg.wait_for_timeout(300)
    # odómetro menor → advertencia, corrección solo con observación
    pg.locator('[data-new]').first.click(); form(pg); pg.fill('.op-form [name=date]','2026-10-06'); pg.fill('.op-form [name=time]','12:00'); pg.fill('.op-form [name=odometer]','126000'); pg.fill('.op-form [name=liters]','50'); pg.fill('.op-form [name=amount]','1200')
    ok('Menor que la recarga anterior' in pg.locator('[data-odo]').inner_text(),'advertencia en vivo de odómetro menor')
    submit(pg); pg.wait_for_selector('.asheet'); ok('Odómetro fuera de secuencia' in pg.locator('.asheet').inner_text(),'advertencia clara antes de guardar'); shot(pg,'n14_odometro')
    pg.locator('.as-btn.destructive').click(); pg.wait_for_timeout(400); ok('motivo de la corrección' in pg.locator('[data-f="notes"] .ferr').inner_text(),'la corrección exige observación')
    pg.fill('.op-form [name=notes]','Cambio de equipo GPS'); submit(pg); pg.wait_for_selector('.asheet'); pg.locator('.as-btn.destructive').click(); pg.wait_for_timeout(700)
    ok(pg.locator('.fuel-row').first.locator('.st',has_text='Corrección').count()==1,'recarga registrada como corrección (reinicia la medición)')
    # editar y eliminar → recálculo
    pg.locator('.fuel-row',has_text='03/10/2026').click(); pg.wait_for_selector('[data-edit]'); pg.locator('[data-edit]').click(); form(pg); pg.fill('.op-form [name=liters]','100'); submit(pg); pg.wait_for_timeout(500)
    ok(pg.locator('.fuel-row',has_text='05/10/2026').inner_text().count('2.81 km/L')==1,'editar una parcial (80 → 100 L) recalcula el periodo: 900/320 = 2.81 km/L')
    pg.locator('.fuel-row',has_text='03/10/2026').click(); pg.wait_for_selector('[data-del]'); pg.locator('[data-del]').click(); pg.locator('.as-btn.destructive').click(); pg.wait_for_timeout(600)
    ok(pg.locator('.fuel-row',has_text='05/10/2026').inner_text().count('4.09 km/L')==1,'eliminar una recarga recalcula: 900/220 = 4.09 km/L')
    ok(pg.locator('svg.chart').count()>=3,'gráficas: rendimiento, litros, gasto y odómetro'); shot(pg,'n15_unidad')
    pg.locator('.chart-box').first.scroll_into_view_if_needed(); shot(pg,'n16_graficas')
    # segunda unidad y comparación
    pg.goto(BASE+'#/operacion/combustible'); pg.wait_for_timeout(600); pg.locator('.unit-chips .chip',has_text='U08').click(); pg.wait_for_timeout(600)
    recarga(pg,'2026-10-02','07:00',88000,280,6888,True); recarga(pg,'2026-10-06','07:30',88820,290,7134,True)
    pg.goto(BASE+'#/operacion/combustible'); pg.wait_for_timeout(700)
    rows=[x.inner_text().split('\n')[0] for x in pg.locator('.list .row .unit-badge').all()]; ok(rows==['U21','U08'],'comparar: mejor rendimiento primero '+str(rows))
    pg.locator('[data-sort="amount"]').click(); pg.wait_for_timeout(200); rows=[x.inner_text() for x in pg.locator('.list .row .unit-badge').all()]; ok(rows[0]=='U08','ordenar por mayor gasto: U08 ($14,022) antes que U21 ($13,940)')
    ok('Unidades activas\n2' in pg.locator('.tiles').first.inner_text(),'resumen de flota del mes'); shot(pg,'n17_flota')
    pg.locator('[data-per="mesAnt"]').click(); pg.wait_for_timeout(200); ok('No hay recargas en este periodo' in pg.locator('.page').inner_text(),'filtro de periodo (mes anterior sin recargas)')
    # Excel
    pg.locator('[data-per="mes"]').click(); pg.locator('[data-export]').click(); pg.wait_for_selector('[data-xgo]'); pg.locator('[data-xgo]').click(); pg.wait_for_selector('[data-xs]',timeout=10000); shot(pg,'n18_excel')
    with pg.expect_download() as d: pg.locator('[data-xs="0"]').click()
    import openpyxl, shutil; shutil.copy(d.value.path(),'/tmp/dl.xlsx'); wb=openpyxl.load_workbook('/tmp/dl.xlsx'); R=wb['Recargas']
    ok(wb.sheetnames==['Resumen general','Recargas','Resumen por unidad'] and R.freeze_panes=='A7' and R.auto_filter.ref and len(R._images)==1,'Excel: 3 hojas, panel fijo, filtros y logotipo | '+d.value.suggested_filename)
    ok(sum(1 for r in R.iter_rows(min_row=7) if r[2].value in ('U21','U08'))==6,'Excel: 6 recargas del mes')
    bk=pg.evaluate('''async()=>{const m=await import('/src/services/backup.js');const f=await m.exportBackup({includeMedia:false});const o=JSON.parse(await f.text());return {fuel:o.data.fuelRecords.length,avatar:o.data.attachments.filter(a=>a.kind==='avatar').length,types:o.data.trailers.filter(t=>t.type).length,rfc:o.data.operators.filter(x=>x.rfc).length}}''')
    ok(bk=={'fuel':7,'avatar':1,'types':4,'rfc':1},'respaldo incluye recargas, foto del operador, tipos de remolque y RFC: '+str(bk))
    pg.emulate_media(color_scheme='dark'); pg.goto(BASE+'#/'); pg.wait_for_timeout(700); shot(pg,'n19_oscuro_inicio'); pg.goto(BASE+'#/operacion/combustible/'+pg.evaluate("(async()=>{const m=await import('/src/services/fuel.js');return m.vehicles().find(v=>v.label==='U21').id})()")); pg.wait_for_timeout(900); shot(pg,'n20_oscuro_unidad')
    b.close()
finally: srv.terminate()
print('\n'.join(log)); print('errores:','; '.join(errs) or 'ninguno')
