/*
 * Tarifario de transporte SENCILLO (Tolva y Jaula) por zona, ciudad de origen y planta destino. Importes en pesos (MXN).
 * Origen: hoja «PERCONSUR_PROPUESTA.xlsx» (columna PERCONSUR). Solo se registran las combinaciones que tienen monto;
 * las que venían vacías (Tolva/Jaula full, Torton y rutas sin tarifa) no se incluyen.
 * Limpieza aplicada al importar: nombres con espacios y acentos, «Bajio zona C» = «Bajío zona C», «Pacifico» = «Pacífico» y
 * plantas con el nombre del catálogo (Planta Nextipac, Planta Villagrán, Planta Los Mochis).
 * Formato de cada renglón: [zona, ciudad de origen, planta destino, tipo de unidad, importe en pesos].
 */
export const TARIFF_CONFIG = 'Sencillo';
export const TARIFF_SOURCE = 'PERCONSUR_PROPUESTA.xlsx';

export const TARIFFS = [
  ['Occidente', 'Sayula', 'Planta Nextipac', 'Tolva', 21200],
  ['Occidente', 'Sayula', 'Planta Nextipac', 'Jaula', 17200],
  ['Occidente', 'Sayula', 'Planta Villagrán', 'Tolva', 49000],
  ['Occidente', 'Sayula', 'Planta Villagrán', 'Jaula', 40500],
  ['Occidente', 'Etzatlán', 'Planta Nextipac', 'Tolva', 17000],
  ['Occidente', 'Etzatlán', 'Planta Nextipac', 'Jaula', 14500],
  ['Occidente', 'Etzatlán', 'Planta Villagrán', 'Tolva', 42500],
  ['Occidente', 'Etzatlán', 'Planta Villagrán', 'Jaula', 34500],
  ['Occidente', 'Etzatlán', 'Planta Los Mochis', 'Tolva', 80000],
  ['Occidente', 'Etzatlán', 'Planta Los Mochis', 'Jaula', 70000],
  ['Occidente', 'San Juan de Abajo, Nay.', 'Planta Nextipac', 'Tolva', 38500],
  ['Occidente', 'San Juan de Abajo, Nay.', 'Planta Nextipac', 'Jaula', 31200],
  ['Occidente', 'San Juan de Abajo, Nay.', 'Planta Villagrán', 'Tolva', 61500],
  ['Occidente', 'San Juan de Abajo, Nay.', 'Planta Villagrán', 'Jaula', 49000],
  ['Occidente', 'San Juan de Abajo, Nay.', 'Planta Los Mochis', 'Tolva', 77500],
  ['Occidente', 'San Juan de Abajo, Nay.', 'Planta Los Mochis', 'Jaula', 60000],
  ['Occidente', 'Villa Hidalgo, Nay.', 'Planta Nextipac', 'Tolva', 38500],
  ['Occidente', 'Villa Hidalgo, Nay.', 'Planta Nextipac', 'Jaula', 28500],
  ['Occidente', 'Villa Hidalgo, Nay.', 'Planta Villagrán', 'Tolva', 54600],
  ['Occidente', 'Villa Hidalgo, Nay.', 'Planta Villagrán', 'Jaula', 45000],
  ['Occidente', 'Villa Hidalgo, Nay.', 'Planta Los Mochis', 'Tolva', 70000],
  ['Occidente', 'Villa Hidalgo, Nay.', 'Planta Los Mochis', 'Jaula', 59500],
  ['Pacífico', 'Los Mochis, Sin.', 'Planta Nextipac', 'Tolva', 80500],
  ['Pacífico', 'Los Mochis, Sin.', 'Planta Nextipac', 'Jaula', 70000],
  ['Pacífico', 'Los Mochis, Sin.', 'Planta Villagrán', 'Tolva', 89500],
  ['Pacífico', 'Los Mochis, Sin.', 'Planta Villagrán', 'Jaula', 79500],
  ['Pacífico', 'Culiacán, Sin.', 'Planta Nextipac', 'Tolva', 69000],
  ['Pacífico', 'Culiacán, Sin.', 'Planta Nextipac', 'Jaula', 61000],
  ['Pacífico', 'Culiacán, Sin.', 'Planta Villagrán', 'Tolva', 84500],
  ['Pacífico', 'Culiacán, Sin.', 'Planta Villagrán', 'Jaula', 77000],
  ['Pacífico', 'Guasave, Sin.', 'Planta Nextipac', 'Tolva', 72000],
  ['Pacífico', 'Guasave, Sin.', 'Planta Nextipac', 'Jaula', 63000],
  ['Pacífico', 'Guasave, Sin.', 'Planta Villagrán', 'Tolva', 87000],
  ['Pacífico', 'Guasave, Sin.', 'Planta Villagrán', 'Jaula', 79500],
  ['Bajío zona A', 'Cortazar', 'Planta Nextipac', 'Tolva', 41000],
  ['Bajío zona A', 'Cortazar', 'Planta Nextipac', 'Jaula', 32400],
  ['Bajío zona A', 'Cortazar', 'Planta Villagrán', 'Tolva', 15000],
  ['Bajío zona A', 'Cortazar', 'Planta Villagrán', 'Jaula', 12000],
  ['Bajío zona A', 'Villagrán', 'Planta Nextipac', 'Tolva', 39000],
  ['Bajío zona A', 'Villagrán', 'Planta Nextipac', 'Jaula', 32200],
  ['Bajío zona A', 'Villagrán', 'Planta Villagrán', 'Tolva', 14500],
  ['Bajío zona A', 'Villagrán', 'Planta Villagrán', 'Jaula', 12800],
  ['Bajío zona A', 'Juventino Rosas', 'Planta Nextipac', 'Tolva', 39000],
  ['Bajío zona A', 'Juventino Rosas', 'Planta Nextipac', 'Jaula', 33500],
  ['Bajío zona A', 'Juventino Rosas', 'Planta Villagrán', 'Tolva', 15000],
  ['Bajío zona A', 'Juventino Rosas', 'Planta Villagrán', 'Jaula', 13000],
  ['Bajío zona A', 'Celaya (Las Conchas)', 'Planta Nextipac', 'Tolva', 39000],
  ['Bajío zona A', 'Celaya (Las Conchas)', 'Planta Nextipac', 'Jaula', 33500],
  ['Bajío zona A', 'Celaya (Las Conchas)', 'Planta Villagrán', 'Tolva', 15000],
  ['Bajío zona A', 'Celaya (Las Conchas)', 'Planta Villagrán', 'Jaula', 13000],
  ['Bajío zona A', 'Estrada (Celaya)', 'Planta Nextipac', 'Tolva', 39000],
  ['Bajío zona A', 'Estrada (Celaya)', 'Planta Nextipac', 'Jaula', 32000],
  ['Bajío zona A', 'Estrada (Celaya)', 'Planta Villagrán', 'Tolva', 15000],
  ['Bajío zona A', 'Estrada (Celaya)', 'Planta Villagrán', 'Jaula', 13000],
  ['Bajío zona A', 'Sarabia (Villagrán)', 'Planta Nextipac', 'Tolva', 38200],
  ['Bajío zona A', 'Sarabia (Villagrán)', 'Planta Nextipac', 'Jaula', 33000],
  ['Bajío zona A', 'Sarabia (Villagrán)', 'Planta Villagrán', 'Tolva', 14500],
  ['Bajío zona A', 'Sarabia (Villagrán)', 'Planta Villagrán', 'Jaula', 13000],
  ['Bajío zona B', 'Salamanca', 'Planta Nextipac', 'Tolva', 38200],
  ['Bajío zona B', 'Salamanca', 'Planta Nextipac', 'Jaula', 32000],
  ['Bajío zona B', 'Salamanca', 'Planta Villagrán', 'Tolva', 17500],
  ['Bajío zona B', 'Salamanca', 'Planta Villagrán', 'Jaula', 14000],
  ['Bajío zona B', 'Irapuato', 'Planta Nextipac', 'Tolva', 38200],
  ['Bajío zona B', 'Irapuato', 'Planta Nextipac', 'Jaula', 32100],
  ['Bajío zona B', 'Irapuato', 'Planta Villagrán', 'Tolva', 18000],
  ['Bajío zona B', 'Irapuato', 'Planta Villagrán', 'Jaula', 14500],
  ['Bajío zona B', 'Comonfort', 'Planta Nextipac', 'Tolva', 41000],
  ['Bajío zona B', 'Comonfort', 'Planta Nextipac', 'Jaula', 36000],
  ['Bajío zona B', 'Comonfort', 'Planta Villagrán', 'Tolva', 19000],
  ['Bajío zona B', 'Comonfort', 'Planta Villagrán', 'Jaula', 15800],
  ['Bajío zona B', 'Valle de Santiago', 'Planta Nextipac', 'Tolva', 40000],
  ['Bajío zona B', 'Valle de Santiago', 'Planta Nextipac', 'Jaula', 32500],
  ['Bajío zona B', 'Valle de Santiago', 'Planta Villagrán', 'Tolva', 18500],
  ['Bajío zona B', 'Valle de Santiago', 'Planta Villagrán', 'Jaula', 15000],
  ['Bajío zona A', 'Jaral del Progreso', 'Planta Nextipac', 'Tolva', 40000],
  ['Bajío zona A', 'Jaral del Progreso', 'Planta Nextipac', 'Jaula', 33000],
  ['Bajío zona A', 'Jaral del Progreso', 'Planta Villagrán', 'Tolva', 15000],
  ['Bajío zona A', 'Jaral del Progreso', 'Planta Villagrán', 'Jaula', 12000],
  ['Bajío zona C', 'Romita', 'Planta Nextipac', 'Tolva', 40500],
  ['Bajío zona C', 'Romita', 'Planta Nextipac', 'Jaula', 35000],
  ['Bajío zona C', 'Romita', 'Planta Villagrán', 'Tolva', 20000],
  ['Bajío zona C', 'Romita', 'Planta Villagrán', 'Jaula', 16000],
  ['Bajío zona C', 'Silao', 'Planta Nextipac', 'Tolva', 40500],
  ['Bajío zona C', 'Silao', 'Planta Nextipac', 'Jaula', 34000],
  ['Bajío zona C', 'Silao', 'Planta Villagrán', 'Tolva', 20000],
  ['Bajío zona C', 'Silao', 'Planta Villagrán', 'Jaula', 16000],
  ['Bajío zona C', 'Abasolo', 'Planta Nextipac', 'Tolva', 40000],
  ['Bajío zona C', 'Abasolo', 'Planta Nextipac', 'Jaula', 33000],
  ['Bajío zona C', 'Abasolo', 'Planta Villagrán', 'Tolva', 20000],
  ['Bajío zona C', 'Abasolo', 'Planta Villagrán', 'Jaula', 16500],
  ['Bajío zona D', 'Dolores Hidalgo', 'Planta Nextipac', 'Tolva', 45000],
  ['Bajío zona D', 'Dolores Hidalgo', 'Planta Nextipac', 'Jaula', 40000],
  ['Bajío zona D', 'Dolores Hidalgo', 'Planta Villagrán', 'Tolva', 23000],
  ['Bajío zona D', 'Dolores Hidalgo', 'Planta Villagrán', 'Jaula', 20000],
  ['Bajío zona C', 'San Miguel de Allende', 'Planta Nextipac', 'Tolva', 43000],
  ['Bajío zona C', 'San Miguel de Allende', 'Planta Nextipac', 'Jaula', 35500],
  ['Bajío zona C', 'San Miguel de Allende', 'Planta Villagrán', 'Tolva', 22000],
  ['Bajío zona C', 'San Miguel de Allende', 'Planta Villagrán', 'Jaula', 19000],
  ['Bajío zona B', 'Salvatierra', 'Planta Nextipac', 'Tolva', 40000],
  ['Bajío zona B', 'Salvatierra', 'Planta Nextipac', 'Jaula', 33000],
  ['Bajío zona B', 'Salvatierra', 'Planta Villagrán', 'Tolva', 18500],
  ['Bajío zona B', 'Salvatierra', 'Planta Villagrán', 'Jaula', 14800],
  ['Bajío zona D', 'San Luis de la Paz', 'Planta Nextipac', 'Tolva', 45000],
  ['Bajío zona D', 'San Luis de la Paz', 'Planta Nextipac', 'Jaula', 40000],
  ['Bajío zona D', 'San Luis de la Paz', 'Planta Villagrán', 'Tolva', 23500],
  ['Bajío zona D', 'San Luis de la Paz', 'Planta Villagrán', 'Jaula', 20500],
  ['Bajío zona D', 'San Diego de la Unión', 'Planta Nextipac', 'Tolva', 45000],
  ['Bajío zona D', 'San Diego de la Unión', 'Planta Nextipac', 'Jaula', 39000],
  ['Bajío zona D', 'San Diego de la Unión', 'Planta Villagrán', 'Tolva', 23500],
  ['Bajío zona D', 'San Diego de la Unión', 'Planta Villagrán', 'Jaula', 20000],
  ['Bajío zona C', 'Huimilpan, Qro.', 'Planta Nextipac', 'Tolva', 45000],
  ['Bajío zona C', 'Huimilpan, Qro.', 'Planta Nextipac', 'Jaula', 38000],
  ['Bajío zona C', 'Huimilpan, Qro.', 'Planta Villagrán', 'Tolva', 23000],
  ['Bajío zona C', 'Huimilpan, Qro.', 'Planta Villagrán', 'Jaula', 19500],
  ['Bajío zona B', 'Apaseo el Grande (incluye Obrajuelos)', 'Planta Nextipac', 'Tolva', 42000],
  ['Bajío zona B', 'Apaseo el Grande (incluye Obrajuelos)', 'Planta Nextipac', 'Jaula', 36000],
  ['Bajío zona B', 'Apaseo el Grande (incluye Obrajuelos)', 'Planta Villagrán', 'Tolva', 22000],
  ['Bajío zona B', 'Apaseo el Grande (incluye Obrajuelos)', 'Planta Villagrán', 'Jaula', 17500],
  ['Bajío zona B', 'Apaseo el Alto (incluye San Antonio Calichar)', 'Planta Nextipac', 'Tolva', 42000],
  ['Bajío zona B', 'Apaseo el Alto (incluye San Antonio Calichar)', 'Planta Nextipac', 'Jaula', 36000],
  ['Bajío zona B', 'Apaseo el Alto (incluye San Antonio Calichar)', 'Planta Villagrán', 'Tolva', 22000],
  ['Bajío zona B', 'Apaseo el Alto (incluye San Antonio Calichar)', 'Planta Villagrán', 'Jaula', 17500],
  ['Bajío zona A', 'Victoria de Cortazar', 'Planta Nextipac', 'Tolva', 42000],
  ['Bajío zona A', 'Victoria de Cortazar', 'Planta Nextipac', 'Jaula', 34000],
  ['Bajío zona A', 'Victoria de Cortazar', 'Planta Villagrán', 'Tolva', 17200],
  ['Bajío zona A', 'Victoria de Cortazar', 'Planta Villagrán', 'Jaula', 13500],
  ['Bajío zona B', 'Armadillo', 'Planta Nextipac', 'Tolva', 42000],
  ['Bajío zona B', 'Armadillo', 'Planta Nextipac', 'Jaula', 34500],
  ['Bajío zona B', 'Armadillo', 'Planta Villagrán', 'Tolva', 16500],
  ['Bajío zona B', 'Armadillo', 'Planta Villagrán', 'Jaula', 13000],
  ['Bajío zona B', 'San Nicolás, Cupareo, San Pedro de los Naranjos, Hermosillo, Santiago Maravatío', 'Planta Nextipac', 'Tolva', 42000],
  ['Bajío zona B', 'San Nicolás, Cupareo, San Pedro de los Naranjos, Hermosillo, Santiago Maravatío', 'Planta Nextipac', 'Jaula', 34500],
  ['Bajío zona B', 'San Nicolás, Cupareo, San Pedro de los Naranjos, Hermosillo, Santiago Maravatío', 'Planta Villagrán', 'Tolva', 18000],
  ['Bajío zona B', 'San Nicolás, Cupareo, San Pedro de los Naranjos, Hermosillo, Santiago Maravatío', 'Planta Villagrán', 'Jaula', 16000],
  ['Bajío zona D', 'Pénjamo', 'Planta Nextipac', 'Tolva', 40000],
  ['Bajío zona D', 'Pénjamo', 'Planta Nextipac', 'Jaula', 33500],
  ['Bajío zona D', 'Pénjamo', 'Planta Villagrán', 'Tolva', 23500],
  ['Bajío zona D', 'Pénjamo', 'Planta Villagrán', 'Jaula', 19500],
  ['Bajío zona D', 'San Francisco del Rincón', 'Planta Nextipac', 'Tolva', 42000],
  ['Bajío zona D', 'San Francisco del Rincón', 'Planta Nextipac', 'Jaula', 33500],
  ['Bajío zona D', 'San Francisco del Rincón', 'Planta Villagrán', 'Tolva', 21000],
  ['Bajío zona D', 'San Francisco del Rincón', 'Planta Villagrán', 'Jaula', 18500],
  ['Bajío zona D', 'Purísima del Rincón', 'Planta Nextipac', 'Tolva', 42000],
  ['Bajío zona D', 'Purísima del Rincón', 'Planta Nextipac', 'Jaula', 35000],
  ['Bajío zona D', 'Purísima del Rincón', 'Planta Villagrán', 'Tolva', 21500],
  ['Bajío zona D', 'Purísima del Rincón', 'Planta Villagrán', 'Jaula', 18500],
  ['Bajío zona D', 'Manuel Doblado', 'Planta Nextipac', 'Tolva', 42000],
  ['Bajío zona D', 'Manuel Doblado', 'Planta Nextipac', 'Jaula', 35000],
  ['Bajío zona D', 'Manuel Doblado', 'Planta Villagrán', 'Tolva', 21500],
  ['Bajío zona D', 'Manuel Doblado', 'Planta Villagrán', 'Jaula', 18000],
  ['Bajío zona C', 'Acámbaro', 'Planta Nextipac', 'Tolva', 42000],
  ['Bajío zona C', 'Acámbaro', 'Planta Nextipac', 'Jaula', 36000],
  ['Bajío zona C', 'Acámbaro', 'Planta Villagrán', 'Tolva', 21500],
  ['Bajío zona C', 'Acámbaro', 'Planta Villagrán', 'Jaula', 17500],
  ['Bajío zona D', 'León', 'Planta Nextipac', 'Tolva', 42000],
  ['Bajío zona D', 'León', 'Planta Nextipac', 'Jaula', 35200],
  ['Bajío zona D', 'León', 'Planta Villagrán', 'Tolva', 21500],
  ['Bajío zona D', 'León', 'Planta Villagrán', 'Jaula', 17500],
  ['Bajío zona C', 'Tequisquiapan, Qro.', 'Planta Nextipac', 'Tolva', 48000],
  ['Bajío zona C', 'Tequisquiapan, Qro.', 'Planta Nextipac', 'Jaula', 39500],
  ['Bajío zona C', 'Tequisquiapan, Qro.', 'Planta Villagrán', 'Tolva', 23500],
  ['Bajío zona C', 'Tequisquiapan, Qro.', 'Planta Villagrán', 'Jaula', 21000],
  ['Bajío zona C', 'Cuerámaro', 'Planta Nextipac', 'Tolva', 42000],
  ['Bajío zona C', 'Cuerámaro', 'Planta Nextipac', 'Jaula', 34000],
  ['Bajío zona C', 'Cuerámaro', 'Planta Villagrán', 'Tolva', 21000],
  ['Bajío zona C', 'Cuerámaro', 'Planta Villagrán', 'Jaula', 18000],
  ['Bajío zona A', 'Pueblo Nuevo', 'Planta Nextipac', 'Tolva', 40000],
  ['Bajío zona A', 'Pueblo Nuevo', 'Planta Nextipac', 'Jaula', 34500],
  ['Bajío zona A', 'Pueblo Nuevo', 'Planta Villagrán', 'Tolva', 21000],
  ['Bajío zona A', 'Pueblo Nuevo', 'Planta Villagrán', 'Jaula', 17500],
];
